services:
  agent-zero:
    container_name: agent-zero
    image: frdel/agent-zero:latest  # Always pull latest version
    volumes:
      - ./agent-zero:/a0
    ports:
      - "50080:80"
    restart: unless-stopped